"""add_tracker_pairing_codes_and_update_devices

Revision ID: 47b1b02f70f8
Revises: 161a0d57db27
Create Date: 2026-06-25 11:15:58.564997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '47b1b02f70f8'
down_revision: Union[str, Sequence[str], None] = '161a0d57db27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_index_if_table_exists(
    index_name: str,
    table_name: str,
    column_name: str,
    using: str = "gist"
) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = '{table_name}'
            ) THEN
                EXECUTE 'CREATE INDEX IF NOT EXISTS {index_name}
                ON {table_name} USING {using} ({column_name})';
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_pairing_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('daycare_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', 'CANCELLED', name='pairingcodestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['daycare_id'], ['daycares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_pairing_codes_code'), 'tracker_pairing_codes', ['code'], unique=True)
    op.add_column('devices', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('tracking_token_hash', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('paired_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_devices_code'), 'devices', ['code'], unique=True)
    # ### end Alembic commands ###

    create_index_if_table_exists(
        "idx_daycares_area",
        "daycares",
        "area"
    )

    create_index_if_table_exists(
        "idx_child_locations_point",
        "child_locations",
        "point"
    )

    create_index_if_table_exists(
        "idx_current_child_locations_point",
        "current_child_locations",
        "point"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_code'), table_name='devices')
    op.drop_column('devices', 'paired_at')
    op.drop_column('devices', 'last_seen_at')
    op.drop_column('devices', 'tracking_token_hash')
    op.drop_column('devices', 'code')
    op.drop_index(op.f('ix_tracker_pairing_codes_code'), table_name='tracker_pairing_codes')
    op.drop_table('tracker_pairing_codes')
    # ### end Alembic commands ###