"""refactor_users_devices_alerts

Revision ID: 5105305fc7f9
Revises: 47b1b02f70f8
Create Date: 2026-07-05 10:29:53.991857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5105305fc7f9'
down_revision: Union[str, Sequence[str], None] = '47b1b02f70f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_index_if_table_exists(
    index_name: str,
    table_name: str,
    column_name: str,
    using: str = "gist"
) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = '{table_name}'
            ) THEN
                EXECUTE 'CREATE INDEX IF NOT EXISTS {index_name}
                ON {table_name} USING {using} ({column_name})';
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracker_pairing_codes', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('tracker_pairing_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tracker_pairing_codes', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tracker_pairing_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracker_pairing_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('daycare_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('users_guardian_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'daycares', ['daycare_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'guardian_id')
    # ### end Alembic commands ###

    # --- Cambios manuales para el Enum userrole ---
    op.execute("ALTER TYPE userrole RENAME TO userrole_old")
    op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'DAYCARE_MANAGER', 'OPERATOR', 'MONITOR')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE text USING role::text")
    op.execute("UPDATE users SET role = 'MONITOR' WHERE role IN ('GUARDIAN', 'TRACKING_DEVICE')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    op.execute("DROP TYPE userrole_old")

    create_index_if_table_exists(
        "idx_daycares_area",
        "daycares",
        "area"
    )

    create_index_if_table_exists(
        "idx_child_locations_point",
        "child_locations",
        "point"
    )

    create_index_if_table_exists(
        "idx_current_child_locations_point",
        "current_child_locations",
        "point"
    )


def downgrade() -> None:
    # --- Cambios manuales para el Enum userrole ---
    op.execute("ALTER TYPE userrole RENAME TO userrole_old")
    op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'DAYCARE_MANAGER', 'GUARDIAN', 'TRACKING_DEVICE')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE text USING role::text")
    op.execute("UPDATE users SET role = 'GUARDIAN' WHERE role IN ('OPERATOR', 'MONITOR')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    op.execute("DROP TYPE userrole_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('guardian_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_guardian_id_fkey'), 'users', 'guardians', ['guardian_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'daycare_id')
    op.alter_column('tracker_pairing_codes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracker_pairing_codes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracker_pairing_codes', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tracker_pairing_codes', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tracker_pairing_codes', 'code',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###