"""update_guardian_auth_flow

Revision ID: d88ebcc1e86c
Revises: cdc01f52dad2
Create Date: 2026-06-24 18:59:42.171216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd88ebcc1e86c'
down_revision: Union[str, Sequence[str], None] = 'cdc01f52dad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_index_if_table_exists(
    index_name: str,
    table_name: str,
    column_name: str,
    using: str = "gist"
) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = '{table_name}'
            ) THEN
                EXECUTE 'CREATE INDEX IF NOT EXISTS {index_name}
                ON {table_name} USING {using} ({column_name})';
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('guardians', sa.Column('pin_hash', sa.String(length=255), nullable=False))
    op.add_column('guardians', sa.Column('must_change_pin', sa.Boolean(), nullable=False))
    op.add_column('guardians', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('guardians', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('guardians', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_guardians_code'), 'guardians', ['code'], unique=True)
    # ### end Alembic commands ###

    create_index_if_table_exists(
        "idx_daycares_area",
        "daycares",
        "area"
    )

    create_index_if_table_exists(
        "idx_child_locations_point",
        "child_locations",
        "point"
    )

    create_index_if_table_exists(
        "idx_current_child_locations_point",
        "current_child_locations",
        "point"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardians_code'), table_name='guardians')
    op.drop_column('guardians', 'locked_until')
    op.drop_column('guardians', 'failed_login_attempts')
    op.drop_column('guardians', 'last_login_at')
    op.drop_column('guardians', 'must_change_pin')
    op.drop_column('guardians', 'pin_hash')
    op.drop_column('guardians', 'code')
    # ### end Alembic commands ###